name: ptr_ci

on: [push, pull_request]

jobs:
  build:
    name: Running python ${{ matrix.python-version }} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4.2.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Print Python Version
      run: python --version && which python

    - name: Update pip, setuptools + wheels
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install ptr

    - name: Run ptr CI
      env:
       pythonioencoding: utf-8
      run: |
        ptr --print-cov

